version: "3"

services:
  # NODE_EXPRESS
  my-node:
    container_name: node-napa
    build: ./server
    restart: always
    links:
      - my-mongo
    ports:
      - "3000:3000"
    volumes:
      - ./server:/node/server
  # MONGO
  my-mongo:
    container_name: mongo-napa
    image: "mongo:latest"
    restart: always
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
