version: "3"

#NETWORK
networks:
  napa-network:
    driver: "bridge"

# VOLUMES
# volumes:
#   dir-node-mongo:
#     driver: local
#     driver_opts:
#       type: none
#       device: D:\Cong_Viec\NapaGlobal\Training_Napa\dockerNodeMongo
#       o: bind

services:
  # NODE_EXPRESS
  my-node:
    container_name: node-napa
    build: ./
    restart: always
    links:
      - my-mongo
    ports:
      - "8181:8181"
    volumes:
      - ./:/usr/src/app
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
  # MONGO
  my-mongo:
    container_name: mongo-napa
    image: "mongo:latest"
    restart: always
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
